---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
  name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
  name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jcarvaja/quarkus-helm-integration-tests-kubernetes-minimal-plugin:latest
          imagePullPolicy: Always
          name: quarkus-helm-integration-tests-kubernetes-minimal-plugin
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
