apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  myvalue: "Hello World"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: names-configmap
data:
  myvalue: "Hello World"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: quarkus-helm-integration-tests-kubernetes-with-templates
                port:
                  name: http
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: another-unused-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: another-service
                port:
                  name: http
            path: /
            pathType: Prefix