= Using Quarkus Helm

include::./includes/attributes.adoc[]

:config-file: application.properties
:extension-status: preview

https://helm.sh/[Helm] is the package manager for Kubernetes that help to find, share, and use software that is built for Kubernetes.

Under the hood, the Quarkus Helm extension uses https://dekorate.io/[Dekorate] to generate the Helm chart manifests at build time.

== Prerequisites

To complete this guide, you need:

* roughly 10 minutes
* an IDE
* JDK 11+ installed with `JAVA_HOME` configured appropriately
* Apache Maven {maven-version}
* Docker installed

== Create a Quarkus application with the Helm extension

[source,bash,subs=attributes+]
----
mvn io.quarkus.platform:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=helm-quickstart \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello" \
    -Dextensions="resteasy,kubernetes,helm"
cd helm-quickstart
----

If you already have your Quarkus project configured, you can add the `helm` extension to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="helm"
----

This will add the following to your `pom.xml`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.helm</groupId>
    <artifactId>quarkus-helm</artifactId>
    <version>{quarkus-helm-version}</version>
</dependency>
----

Finally, build your application by running the following command:

[source,bash]
----
mvn clean package
----

[[configuration-reference]]
== Configuration Reference

include::includes/quarkus-helm.adoc[]

== References

* https://helm.sh/[Helm]
* https://dekorate.io/[Dekorate]
